/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Lihini
 */
public class RecoverI extends javax.swing.JFrame {

    /**
     * Creates new form SecurityQuestions
     */
   
 

    public RecoverI() {
        initComponents();
    }
    public void close()
    {
    WindowEvent closeWindow = new WindowEvent(this , WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
  
     
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        txtmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jsearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtq1 = new javax.swing.JLabel();
        jans1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtq2 = new javax.swing.JLabel();
        txtq3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jans2 = new javax.swing.JTextField();
        jans3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jsubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jOptionPane1.setMessage("You have not answered the security questions.Please fill the form .Or please click cancle to leave the page without signing up");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtmail.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        txtmail.setText("Email");

        jsearch.setBackground(new java.awt.Color(0, 0, 102));
        jsearch.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jsearch.setForeground(new java.awt.Color(255, 255, 255));
        jsearch.setText("Search");
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });

        jPanel1.setVisible(false);

        txtq1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jLabel2.setText("Answer");

        txtq2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtq3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jLabel3.setText("Answer");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jLabel4.setText("Answer");

        jsubmit.setBackground(new java.awt.Color(0, 0, 102));
        jsubmit.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jsubmit.setForeground(new java.awt.Color(255, 255, 255));
        jsubmit.setText("Submit");
        jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jans1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jans2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtq3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jans3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtq1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(txtq2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(txtq3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jsubmit))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("SECURITY QUESTIONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmail)
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtemail))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jsearch)
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitActionPerformed
        String a1= jans1.getText();
        String a2= jans2.getText();
        String a3= jans3.getText();
        String recovermail=txtemail.getText();
   
       if(a1==null||a2==null||a3==null){
       JOptionPane.showMessageDialog(null, "Please provide the answers");
       }
        else 
        {
        PreparedStatement ps;
        ResultSet rs;
        
        
        String sql = "select A1,A2,A3 from security where Email=? ";
        try {
            ps = DriverManager.getConnection( "jdbc:mysql://localhost:3306/ phamacy","root","").prepareStatement(sql);
            
            ps.setString(1,recovermail);
            
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                //System.out.println(rs.getString(1)+rs.getString(2)+rs.getString(3));
                if(a1.equals(rs.getString(1))&&a2.equals(rs.getString(2))&&a3.equals(rs.getString(3))){
                
                
               ResetPw rp=new ResetPw();
               rp.setVisible(true);
                    ResetPw.email.setText(recovermail);
              this.close();
                
                }
                 else{
                    JOptionPane.showMessageDialog(null, "Provided answers are incorrect please try again");
                }      
               
                   
                    
            }
            
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        }
       
           
      
      
            
            
     
    }//GEN-LAST:event_jsubmitActionPerformed

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
       String recovermail=txtemail.getText();
       
        String PATTERN="^[a-zA-Z0-9]{0,50}[@][a-zA-Z]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match2=patt.matcher(txtemail.getText());
        
       if(recovermail==null){
       JOptionPane.showMessageDialog(null, "Email can't be null");
       }
        else if(!match2.matches())
        {
             JOptionPane.showMessageDialog(null, "Email is in an invalid format");

        }
        else{
           //--------------------------check email is in the database------------------------
           
           
        PreparedStatement ps1;
        ResultSet rs1;
        
        
      
        String sql = "select * from security where Email=?";
        try {
            ps1 = DriverManager.getConnection( "jdbc:mysql://localhost:3306/phamacy ","root","").prepareStatement(sql);
            
            ps1.setString(1, recovermail);
            
            
            rs1 = ps1.executeQuery();
            
            if(rs1.next())
            {
                       
        jPanel1.setVisible(true);
        txtemail.setEnabled(false);
        
        PreparedStatement ps2;
        ResultSet rs2;
        
        
        String sql2 = "select Q1,Q2,Q3 from security where Email=? ";
        try {
            ps2 = DriverManager.getConnection( "jdbc:mysql://localhost:3306/phamacy ","root","").prepareStatement(sql2);
            
            ps2.setString(1,recovermail);
            
            
            rs2 = ps2.executeQuery();
            
            if(rs2.next())
            {
                   txtq1.setText("1."+rs2.getString(1));
                   txtq2.setText("2."+rs2.getString(2));
                   txtq3.setText("3."+rs2.getString(3));
                   
                    
            }
           /* else{
                    JOptionPane.showMessageDialog(null, "fail");
                }*/
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
                   
                    
            }
           /* else{
                    JOptionPane.showMessageDialog(null, "Enterd email is invalid or you have not registered");
                }
            */
        } catch (SQLException ex) {
            System.out.println(ex);
        }
         
  
         
                    
        }
    }//GEN-LAST:event_jsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoverI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoverI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoverI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoverI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverI().setVisible(true);
            }
        }
        
        
        
        );
   
 
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jans1;
    private javax.swing.JTextField jans2;
    private javax.swing.JTextField jans3;
    private javax.swing.JButton jsearch;
    public static javax.swing.JButton jsubmit;
    public javax.swing.JTextField txtemail;
    private javax.swing.JLabel txtmail;
    private javax.swing.JLabel txtq1;
    private javax.swing.JLabel txtq2;
    private javax.swing.JLabel txtq3;
    // End of variables declaration//GEN-END:variables
}
